
cfg = {
    "app_title": "Password keeper v0.1",
    "geometry": "980x550",
    "resizable_width": False,
    "resizable_height": False,
    "base_width": 260,
    "base_height": 30,
    "tg_bot_name": "asdfq232sdfae12",
    "tg_bot_token": "1916679109:AAF7ZLue5nleYSnYi_rM1BoxM4TIYan3zwI",
    "tg_chat_id": "203724149",
    "tg_main_url": "https://api.telegram.org/bot",
    "tg_method": "/sendMessage",
    "justify": "left",
    "tries_to_login": 3,
    "bg1": 'grey',
    "bg2": '#62799e',
    "label_font_1": ('Arial', 12),
    "label_font_2": ('Arial', 14),
    "entry_font_1": ('Arial', 14),
    "btn_font_1": ('Arial', 12, 'bold'),
    'msg': {
        '0': 'Error',
        '1': 'Добро пожаловать ',
        '2': '',
        '3': 'Incorrect login or password',
        '4': 'Password was send to secret TgBot',
        '5': 'Error with sending password to TgBot. Check the internet connection.',
        '6': 'You are already in sys.\nNow you can read from DB and write in to DB.',
        '7': 'No site with that name in DB',
        '8': 'You are not authorizeted. You shoud do it first.',
        '9': 'Successful added data into DB',
        '10': 'Some problem with adding data into DB.\n More info in console.',
        '11': 'You are not authorizeted. You shoud do it first.',
        '12': 'Here you need to:\n1) input values into fields\n2) click the button.',
        '13': 'Name of the site',
        '14': 'Login:',
        '15': 'Password:',
        '16': 'Comment (not necessary):',
        '17': 'Save data into DB',
        '18': 'Comment:',
        '19': 'Get information from DB',
        '20': 'Empty fields. You need fill information about site, login and password.',
        '21': 'Log In',
        '22': 'Logining',
        '23': 'Saving sites in to DB',
        '24': 'Saved sites in DB'
    }
}